# Generated by Django 4.0.2 on 2022-02-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_homebannermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='messege',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(default=None, verbose_name='message'),
            preserve_default=False,
        ),
    ]
